type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  role: String
}

type Category @table {
  name: String!
  createdAt: Timestamp!
  description: String
}

type Report @table {
  title: String!
  description: String!
  status: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  submissionDate: Date
  dueDate: Date
  author: User
  category: Category
}

type ReportFile @table {
  fileName: String!
  fileType: String!
  fileSize: Int!
  fileUrl: String!
  uploadedAt: Timestamp!
  description: String
  report: Report
}

type ReportLog @table {
  action: String!
  timestamp: Timestamp!
  details: String
  report: Report
  user: User
}