query ListAllCategories @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it only lists categories.") {
  categories {
    id
    name
    description
  }
}

query GetReportsByAuthor($authorId: UUID!) @auth(level: USER) {
  reports(where: {authorId: {eq: $authorId}}) {
    id
    title
    description
    status
    dueDate
    category {
      name
    }
  }
}

mutation CreateNewReport($title: String!, $description: String!, $status: String!, $categoryId: UUID!, $dueDate: Date) @auth(level: USER) {
  report_insert(data: {
    title: $title,
    description: $description,
    status: $status,
    categoryId: $categoryId,
    authorId_expr: "auth.uid",
    dueDate: $dueDate,
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  })
}

mutation UpdateReportStatus($reportId: UUID!, $newStatus: String!) @auth(level: USER) {
  report_update(
    key: {id: $reportId},
    data: {
      status: $newStatus,
      updatedAt_expr: "request.time"
    }
  )
}